---

- name: AWS VPC with Cisco ISE
  hosts: localhost
  gather_facts: yes   # required for `ansible_date_time`
  vars_files:
    vars/main.yaml
  tasks:

  #
  # Limit CIDR IPs to the Lab Network to Prevent Public Internet Access!
  #

  - name: Show VPC(s)
    amazon.aws.ec2_vpc_net:
      name: "{{ aws_vpc_name }}"
      cidr_block:  "{{ aws_vpc_cidr }}"
      region: "{{ aws_region }}"
    register: vpc
  
#  - name: Show Public Subnet(s)
#    amazon.aws.ec2_vpc_subnet_info:
#      filters:
#        "tag:Name": zer0k_pod{{ pod_id }}_Public_Subnet
#    register: subnet_public
#  
#  - debug:
#      var: subnet_public.subnets[0].cidr_block

  - name: Show Transit Gateway(s)
    community.aws.ec2_transit_gateway_info:
      filters:
        transit-gateway-id: "{{ transit_gateway_id }}"
    register: transit_gateway
  
  - debug:
      var: transit_gateway

  - name: Show Private Subnet(s)
    amazon.aws.ec2_vpc_subnet_info:
      filters:
        "tag:Name": zer0k_pod{{ pod_id }}_Private_Subnet
    register: subnet_private
  
  - debug:
      var: subnet_private.subnets[0].cidr_block


  - name: Create SG-ISE Security Group
    amazon.aws.ec2_group:
      name: zer0k_pod{{ pod_id }}_SG-ISE
      description: zer0k_pod{{ pod_id }}_SG-ISE
      # vpc_id: "{{ vpcs.vpcs[0].id }}"
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{ aws_region }}"
      rules:
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip: 10.{{ pod_id }}.0.0/16
        rule_desc: Allow all traffic within VPC
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
        rule_desc: Allow SSH from anywhere
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip: 172.16.0.0/12
        rule_desc: Allow all traffic from on-premises
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0    # any
          rule_desc: Allow All
      tags:
        Name: "{{ project_name }}"
        project: "{{ project_name }}"
        # start_date: "{{ ansible_date_time.date }}"
    register: sg_ise
    tags:
    - sg
    - security_group


  - name: Create ISE 3.2 Instance in AWS
    loop: "{{ ise_nodes }}"
    amazon.aws.ec2_instance:
      state: present
      region: "{{ aws_region }}"
      vpc_subnet_id: "{{ subnet_private.subnets[0].id }}"
      image_id: "{{ aws_ise_ami }}"
      instance_type: "{{ item.instance_type | default( aws_ise_instance_type ) }}"
      key_name: "{{ ssh_keypair_name }}"
      network:
        assign_public_ip: no
        delete_on_termination: yes
        # below references ./vars/main.yaml line 84 - private_ip which is statically defined as desired ISE IP
        # note that "item" references an index in an array as part of a loop, similar to 'array(i)' in C++
        private_ip_address: "{{ item.private_ip}}"
      security_group: "{{ sg_ise.group_id }}"
      volumes:
        - device_name: /dev/sda1
          ebs:
            delete_on_termination: true
            volume_size: "{{ item.volume_size | default( 300 ) }}"
      wait: yes
      tags:
        # note that "item" references an index in an array as part of a loop, similar to 'array(i)' in C++
        Name: "{{ item.name }}"
        product: "ISE"
        hostname: "{{ item.name }}"
        project: "{{ project_name }}"
        start_date: "{{ ansible_date_time.date }}"
        role: "{{ item.role | default( '') }}"
        personas: "{{ item.personas | default( 'standalone') }}"
      user_data: "hostname={{ item.name | lower }}\nprimarynameserver={{ ise_dns_server }}\ndnsdomain={{ domain_name }}\nntpserver={{ ise_ntp_server }}\ntimezone={{ ise_timezone }}\nusername={{ ise_username }}\npassword={{ ise_password }}"
    register: instances

  - name: Show ISE Instances
    ansible.builtin.debug: var=instances




  #
  # Advertise the same internal IP for public and private DNS
  #
  #- name: Add public DNS entry for the ISE node(s)
    #loop: "{{ ise_nodes }}"
    #community.aws.route53:
      #state: present
      #zone: "{{ domain_name }}"
      #hosted_zone_id: "{{ ise_route53_host_id }}"
      #record: "{{ item.name }}.{{ domain_name }}"
      #overwrite: yes
      #private_zone: no
      #type: A
      #ttl: 7200
      #value: "{{ item.private_ip }}"
      #wait: no

  - name: Add private DNS entry for the ISE node(s)
    loop: "{{ ise_nodes }}"
    community.aws.route53:
      state: present
      #zone: "{{ domain_name }}"
      hosted_zone_id: "{{ ise_route53_host_id }}"
      record: "{{ item.name }}.{{ domain_name }}"
      overwrite: yes
      private_zone: yes
      type: A
      ttl: 7200
      value: "{{ item.private_ip }}"
      wait: no




  - name: Show SSH Commands for ISE Instances
    loop: "{{ ise_nodes }}"
    ansible.builtin.debug:
      msg: 
      # note that "item" references an index in an array as part of a loop, similar to 'array(i)' in C++
      - "ping {{ item.private_ip }}"
      - "ssh -i {{ ssh_keypair_directory}}/{{ ssh_keypair_name }}.pem {{ ise_username }}@{{ item.private_ip }}"
      - "ping {{ item.name }}.{{ domain_name }}"
      - "ssh -i {{ ssh_keypair_directory}}/{{ ssh_keypair_name }}.pem {{ ise_username }}@{{ item.name }}.{{ domain_name }}"



...
